[2025-05-21T11:00:30.047+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: uhi_index_analytics_pipeline_decompose.perform_base_feature_engineering manual__2025-05-17T05:12:03.413965+00:00 [queued]>
[2025-05-21T11:00:30.068+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: uhi_index_analytics_pipeline_decompose.perform_base_feature_engineering manual__2025-05-17T05:12:03.413965+00:00 [queued]>
[2025-05-21T11:00:30.070+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-05-21T11:00:30.072+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2025-05-21T11:00:30.073+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-05-21T11:00:30.131+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): perform_base_feature_engineering> on 2025-05-17 05:12:03.413965+00:00
[2025-05-21T11:00:30.149+0000] {standard_task_runner.py:55} INFO - Started process 854 to run task
[2025-05-21T11:00:30.157+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'uhi_index_analytics_pipeline_decompose', 'perform_base_feature_engineering', 'manual__2025-05-17T05:12:03.413965+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/uhi_pipeline_dag_decompose.py', '--cfg-path', '/tmp/tmplr5v2gya']
[2025-05-21T11:00:30.158+0000] {standard_task_runner.py:83} INFO - Job 274: Subtask perform_base_feature_engineering
[2025-05-21T11:00:30.269+0000] {task_command.py:388} INFO - Running <TaskInstance: uhi_index_analytics_pipeline_decompose.perform_base_feature_engineering manual__2025-05-17T05:12:03.413965+00:00 [running]> on host ee2bb044a094
[2025-05-21T11:00:30.396+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uhi_index_analytics_pipeline_decompose
AIRFLOW_CTX_TASK_ID=perform_base_feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-05-17T05:12:03.413965+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-17T05:12:03.413965+00:00
[2025-05-21T11:00:30.400+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/uhi_pipeline_dag_decompose.py", line 216, in perform_base_feature_engineering
    features_engineering.calculate_indices(tifffile='landsat_8.tiff', source="landsat_8", savefile='1x1/landsat_indices.tiff', resolution=30)
TypeError: calculate_indices() got an unexpected keyword argument 'tifffile'
[2025-05-21T11:00:30.431+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=uhi_index_analytics_pipeline_decompose, task_id=perform_base_feature_engineering, execution_date=20250517T051203, start_date=20250521T110030, end_date=20250521T110030
[2025-05-21T11:00:30.451+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 274 for task perform_base_feature_engineering (calculate_indices() got an unexpected keyword argument 'tifffile'; 854)
[2025-05-21T11:00:30.497+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-05-21T11:00:30.540+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
