[2025-05-18T09:55:53.522+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: uhi_index_analytics_pipeline_decompose.process_population manual__2025-05-17T05:12:03.413965+00:00 [queued]>
[2025-05-18T09:55:53.613+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: uhi_index_analytics_pipeline_decompose.process_population manual__2025-05-17T05:12:03.413965+00:00 [queued]>
[2025-05-18T09:55:53.617+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-05-18T09:55:53.619+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2025-05-18T09:55:53.626+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-05-18T09:55:53.728+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): process_population> on 2025-05-17 05:12:03.413965+00:00
[2025-05-18T09:55:53.911+0000] {standard_task_runner.py:55} INFO - Started process 78 to run task
[2025-05-18T09:55:54.379+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'uhi_index_analytics_pipeline_decompose', 'process_population', 'manual__2025-05-17T05:12:03.413965+00:00', '--job-id', '222', '--raw', '--subdir', 'DAGS_FOLDER/uhi_pipeline_dag_decompose.py', '--cfg-path', '/tmp/tmpbia13vd5']
[2025-05-18T09:55:54.405+0000] {standard_task_runner.py:83} INFO - Job 222: Subtask process_population
[2025-05-18T09:55:56.427+0000] {task_command.py:388} INFO - Running <TaskInstance: uhi_index_analytics_pipeline_decompose.process_population manual__2025-05-17T05:12:03.413965+00:00 [running]> on host ee2bb044a094
[2025-05-18T09:55:58.584+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uhi_index_analytics_pipeline_decompose
AIRFLOW_CTX_TASK_ID=process_population
AIRFLOW_CTX_EXECUTION_DATE=2025-05-17T05:12:03.413965+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-17T05:12:03.413965+00:00
[2025-05-18T09:55:58.759+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/uhi_pipeline_dag_decompose.py", line 117, in process_population_data
    preprocess.input_data_handle(data["population"], type="population")
TypeError: 'NoneType' object is not subscriptable
[2025-05-18T09:55:58.878+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=uhi_index_analytics_pipeline_decompose, task_id=process_population, execution_date=20250517T051203, start_date=20250518T095553, end_date=20250518T095558
[2025-05-18T09:55:58.969+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 222 for task process_population ('NoneType' object is not subscriptable; 78)
[2025-05-18T09:55:59.128+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-05-18T09:55:59.581+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
